## Przygotowanie do pracy - import pakietu, sprawdzenie wersji

In [1]:
import numpy as np
np.__version__

'1.20.1'

### Pamiętaj, żeby przy wykonywaniu tych zadań posługiwać się dokumentacją biblioteki numpy!
https://numpy.org/doc/

U góry widoczna jest wersja Twojej biblioteki. Wybierz właściwa dokumentację :)

Zad.1. Stworz wektor (ndarray) o wielkosci 10 elementow. 

In [2]:
x1 = np.random.randint(250, size=10)

In [3]:
x1

array([232,  35,  93, 119, 118,  89,   1,  99,  73, 123])

Zad.2. Stworz wektor (ndarray) o wartościach z zakresu od 10 do 109

In [6]:
x2 = np.arange(10, 110)

In [7]:
x2

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100,
       101, 102, 103, 104, 105, 106, 107, 108, 109])

Zad.3. Znajdz w dokumentacji numpy funkcję, która odwróci ten wektor. Ostatni jego element ma się stać pierwszym.

In [8]:
x2_reverse = x2[::-1]

In [9]:
x2_reverse

array([109, 108, 107, 106, 105, 104, 103, 102, 101, 100,  99,  98,  97,
        96,  95,  94,  93,  92,  91,  90,  89,  88,  87,  86,  85,  84,
        83,  82,  81,  80,  79,  78,  77,  76,  75,  74,  73,  72,  71,
        70,  69,  68,  67,  66,  65,  64,  63,  62,  61,  60,  59,  58,
        57,  56,  55,  54,  53,  52,  51,  50,  49,  48,  47,  46,  45,
        44,  43,  42,  41,  40,  39,  38,  37,  36,  35,  34,  33,  32,
        31,  30,  29,  28,  27,  26,  25,  24,  23,  22,  21,  20,  19,
        18,  17,  16,  15,  14,  13,  12,  11,  10])

Zad.4. Stworz macierz 3x3 o wartościach od 0 do 8.

In [14]:
#x3 = np.random.randint(0, 9, size=(3,3))
x3 = ([[0,1,2], [3,4,5], [6,7,8]])

In [15]:
x3

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

Zad.5. Stworz macierz 10x10 z randomowymi wartościami (jak na początku notebooka z zajęć).

Podaj jej max i min. 

In [16]:
x4 = np.random.randint(10, size=(10,10))

In [19]:
x4
x4.max(),x4.min()
x

(9, 0)

Zad.6. Podano następujący skrypt:
    
```python
np.array(np.nan) / 5
```
Jaki będzie jej wynik? Podaj odpowiedź bez wywoływania.

In [20]:
np.array(np.nan) / 5 # dzielenie przez nic (nan) daje nadal nic *(nan)

nan

Zad.7. Dodaj do siebie poniższe macierze

```python
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])
```

In [26]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])
a_b = np.concatenate([a,b])
a_b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12],
       [13, 14, 15]])

Zad.8. Majac ponizsza macierz:

```python
a = np.array([x for x in range(27)])
```
zreshapuj ja do 3 możliwych arrayek 3 wymiarowych. Za kazdym razem nie alokuj wyniku do zmienej.

In [27]:
a = np.array([x for x in range(27)])

In [32]:
a.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Zad.9. Zmień typ danych w arrayce na bool

```python
a = np.array([[1, 0, 0],
              [1, 1, 1],
              [0, 0, 0]])
```

In [33]:
a = np.array([[1, 0, 0],
              [1, 1, 1],
              [0, 0, 0]])
a == 1

array([[ True, False, False],
       [ True,  True,  True],
       [False, False, False]])

Zad.10. Podaj ilość elementów poniższej macierzy, jej kształt i spłaszcz ją.

```python
a2 = np.array([[7,8],
               [9,10],
               [10,11]])
```

In [35]:
a2 = np.array([[7,8],
               [9,10],
               [10,11]])
a2.shape
a2.size

6

Zad.11. Stworz wektor o 10 elementach z randomowymi wartościami oraz przesortuj go.

In [36]:
x4 = np.random.randint(15, size=10)

In [37]:
x4

array([12,  6,  2,  9,  6,  0, 14,  3,  5,  2])

In [38]:
x4[::-1]

array([ 2,  5,  3, 14,  0,  6,  9,  2,  6, 12])

Zad.12. Mając arrayke

Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], 

Sprobuj wyprodukować taka jak poniższa

R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]

In [ ]:
Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
i = 0
lista = []
for element in Z:
    for element in range(Z[i], Z[i+4]):
        while True:
            lista.append(element)
            i += 1
        print(lista)


In [64]:
R = Z.reshape(2, -1)[:5,1:]
R

array([[ 2,  3,  4,  5,  6,  7],
       [ 9, 10, 11, 12, 13, 14]])

Zad.13. Połącz wertykalnie następujące arrayki

```python
a1 = np.array([[1,2],
               [3,4],
               [5,6]])

a2 = np.array([[7,8],
               [9,10],
               [10,11]])
```

In [80]:
a1 = np.array([[1,2],
               [3,4],
               [5,6]])

a2 = np.array([[7,8],
               [9,10],
               [10,11]])
a1_a2 = np.vstack([a1,a2])
a1_a2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [10, 11]])

Zad.14. Jaką funkcją można znaleźć najczęściej występującą wartość w arrayce? Przeszukaj dokumentację :)

In [84]:
x5 = [1,2,3,4,4,4,4,4,5,7,8,9,9,99]

In [85]:
np.bincount(x5).argmax()

4